### ISSUE TITLE
Controller Duration

### ISSUE THREAD

**Issue by absowoot** [srcrip/live_toast#22]
When setting a toast in a controller, it appears that the duration is automatically set to 0 in `LiveToast.Components.flashes`. Could the ability to set options be added?

**Comment by texasdrean** [comment]
Same here, when setting a toast in a controller, it stays forever. Someone to help?

**Comment by andresgutgon** [comment]
I think is because JS hook is working for LiveSocket. But controllers don't use `LiveSocket` in any way afaik

**Comment by srcrip** [comment]
That is correct, flashes will stay until dismissed. That's just how flashes work in Phoenix, which this library doesn't change. The toast system will augment them so that if you use `put_toast` you'll get toasts *instead* of flashes (in the situations where you're not navigating, because that only works with flashes), and those can have duration to be configured to whatever you want. Feel free to open a new issue if you have any other questions. Thanks!
