### ISSUE TITLE
handle_params, push_patch & put_toast

### ISSUE THREAD

**Issue by tomeq93** [srcrip/live_toast#9]
Hey, 
If I use put_toast with combination of push_patch in handle_params I do not have toast visible and it works with default put_flash, any ideas? Thanks, great lib btw :)

**Comment by srcrip** [comment]
Interesting... I will try to replicate but if there's any way you can provide a minimal repro it would help a lot. Thanks!

**Comment by srcrip** [comment]
I have a plan for how to fix this. It should be ready in a few days.

**Comment by srcrip** [comment]
So I have a branch that fully 'fixes' this issue. It is however quite complicated. It requires basically, on every call to `put_toast`, pushing *both* a flash and a toast, and deduping by deleting the flash in the Live Component if it receives an update that contains both a flash and toast of the same kind and message.

That's a little janky, but testable and verifiable I guess. The bigger thing is it also requires passing said toast synchronously through params to the LC. That is a pretty big change that requires a lot to make work. It also means that the param most likely needs to be set to a temporary_assign. That's kind of a problem, cause whatever LV is mounted to the router would have to be responsible for that. We could however make a `__using__` macro that does this and just expect the user to have to put it in there web module LV callback so it fires for every LV.

There is another alternative which is pretty simple: we can also just check the socket for the presence of the `redirected` attribute in `put_toast`, and if it's there, put a flash on instead of a toast. This works great but now the *order* that you call the functions matter. You'd have to call `push_navigate` *before* `put_toast`. It has the advantage of being an extremely simple fix though.

The final option is to just say well, if you want messages to work across navigates just use `put_flash` That's an option, but I don't know if I'm fully satisfied with it.

Like I said, I have a branch that kind of makes it all 'just work', but it's complicated. I think I need to test it more myself and make sure it doesn't add some crazy levels of jank. I can even push it up for others to try at some point soon. If it's not a suitable fix though I think I'll lean towards option two, which is literally a one line change and just requires you to change your user-space code a little bit.

**Comment by sergchernata** [comment]
Can we just auto-dismiss the flash after the redirect, after some number of seconds?

**Comment by MarkoH17** [comment]
@srcrip  Is there any update on this? I didn't see the branch with the experimental fixes in this repo.

**Comment by srcrip** [comment]
@MarkoH17 and others, I've just opened a PR for this issue: https://github.com/srcrip/live_toast/pull/28

Sorry this one was quite a while coming. It was a very complicated problem to get right and I didn't want to rush it out the door.

**Comment by srcrip** [comment]
Closing now since #28 has been implemented.
